apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: nginx-deployment
  namespace: nginx 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngnix-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ngnix-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1 
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx 
spec:
  selector:
    app: ngnix-app
  ports:  
    - protocol: TCP
      port: 80
      targetPort: 80

...

